version: '3.3'
services:
  job_automation:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/job_automation:0.1
    environment:
      TARGET_PATH: /target_path
    volumes:
      - type: bind
        source: /home/allen/DataDisk/Video
        target: /app/target_path
        volume:
          nocopy: true